# Generated by Django 3.2.20 on 2023-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='intent',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
